<?php
/** @var Mage_Core_Block_Template $this **/
?>
<?php
$url = 'http://docs.affirm.com/Integrate_Affirm/Platform_Integration/Magento_Telesales_Integration';
?>

<h3>
    For orders created by Admin, Affirm is only available as a payment method via Telesales at this time. Please contact your Affirm representative for more information.
    <a href="<?php echo $url; ?>"><?php echo $url; ?></a>
</h3>