<?php
/**
 *
 *  * BSD 3-Clause License
 *  *
 *  * Copyright (c) 2018, Affirm
 *  * All rights reserved.
 *  *
 *  * Redistribution and use in source and binary forms, with or without
 *  * modification, are permitted provided that the following conditions are met:
 *  *
 *  *  Redistributions of source code must retain the above copyright notice, this
 *  *   list of conditions and the following disclaimer.
 *  *
 *  *  Redistributions in binary form must reproduce the above copyright notice,
 *  *   this list of conditions and the following disclaimer in the documentation
 *  *   and/or other materials provided with the distribution.
 *  *
 *  *  Neither the name of the copyright holder nor the names of its
 *  *   contributors may be used to endorse or promote products derived from
 *  *   this software without specific prior written permission.
 *  *
 *  * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 *  * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 *  * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *  * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 *  * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 *  * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 *  * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 *  * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

/** @var Affirm_Affirm_Block_Promo_Promo $this **/
?>
<style type="text/css">
    .affirm-banner-container {
        overflow: hidden;
        display: block;
        text-align:center;
    }
    .affirm-banner-container a img {
        display:block;
        margin:auto;
        width:auto;
        height:auto;
    }
</style>
<?php
$size = $this->helper('affirm/promo_data')->getSectionConfig()->getSize();
list($width, $height) = explode('x',$size);
$apiKey = $this->helper('affirm')->getApiKey();
$affirmJsUrl = $this->helper('affirm')->getAffirmJsUrl();
$mfpValue = $this->getMFPValue();
$affirmAssetsUrl = $this->helper('affirm')->getAffirmAssetsUrl();
$pageType = $this->getPageType();
?>
<?php
echo '<div class="affirm-banner-container">
        <a class="affirm-site-modal" ' . (!empty($mfpValue) ? 'data-promo-id="' . $mfpValue . '"' : '') . '' .(!empty($pageType) ? 'data-page-type="' . $pageType . '"' : ''). '>
            <img style="max-width:'. $width .'px; max-height:'. $height .'px; " src="' . $affirmAssetsUrl . '/' . $size .'.png">
        </a>
    </div>';
?>
<script type="text/javascript">
    if (!AFFIRM_AFFIRM.promos.getIsInitialized()) {
        AFFIRM_AFFIRM.promos.initialize("<?php echo $this->helper('affirm')->getApiKey(); ?>",
            "<?php echo $this->helper('affirm')->getAffirmJsUrl(); ?>");
    }
    <?php if ($this->helper('affirm')->isProductConfigurable()): ?>
    if (!AFFIRM_AFFIRM.promos.getIsConfigurableOptionsInitialized()) {
        AFFIRM_AFFIRM.promos.initConfigurableOptions(<?php echo $this->helper('affirm')->getConfigurableBackOrderedInfo(); ?>);
    }
    <?php endif; ?>
    if (!AFFIRM_AFFIRM.promos.getIsScriptLoaded()) {
        AFFIRM_AFFIRM.promos.loadScript();
    }
</script>