<?php
/** @var Affirm_Affirm_Block_Promo_Promo $this **/
?>
<style type="text/css">
    .affirm-banner-container {
        overflow: hidden;
        display: block;
        text-align:center;
    }
    .affirm-banner-container a img {
        display:block;
        margin:auto;
        width:auto;
        height:auto;
    }
</style>
<?php
$size = $this->helper('affirm/promo_data')->getSectionConfig()->getSize();
list($width, $height) = explode('x',$size);
$apiKey = $this->helper('affirm')->getApiKey();
$affirmJsUrl = $this->helper('affirm')->getAffirmJsUrl();
$mfpValue = $this->getMFPValue();
$affirmAssetsUrl = $this->helper('affirm')->getAffirmAssetsUrl();
?>
<?php
echo '<div class="affirm-banner-container">
        <a class="affirm-site-modal" ' . (!empty($mfpValue) ? 'data-promo-id="' . $mfpValue . '"' : '') . '>
            <img style="max-width:'. $width .'px; max-height:'. $height .'px; " src="' . $affirmAssetsUrl . '/' . $size .'.png">
        </a>
    </div>';
?>
<script type="text/javascript">
    if (!AFFIRM_AFFIRM.promos.getIsInitialized()) {
        AFFIRM_AFFIRM.promos.initialize("<?php echo $this->helper('affirm')->getApiKey(); ?>",
            "<?php echo $this->helper('affirm')->getAffirmJsUrl(); ?>");
    }
    <?php if ($this->helper('affirm')->isProductConfigurable()): ?>
    if (!AFFIRM_AFFIRM.promos.getIsConfigurableOptionsInitialized()) {
        AFFIRM_AFFIRM.promos.initConfigurableOptions(<?php echo $this->helper('affirm')->getConfigurableBackOrderedInfo(); ?>);
    }
    <?php endif; ?>
    if (!AFFIRM_AFFIRM.promos.getIsScriptLoaded()) {
        AFFIRM_AFFIRM.promos.loadScript();
    }
</script>