<?php
/** @var Affirm_Affirm_Block_Adminhtml_Compatibility_Tool_ClassRewrites $this **/
$xmlClassRewrites = $this->getXmlClassRewrites();
$codePoolClassRewrites = $this->getCodePoolClassRewrite();

foreach ($xmlClassRewrites as $xmlClassRewrite) {
    foreach ($xmlClassRewrite as $class => $rewriteOptions) {
        if (!empty($rewriteOptions['class'])) {
            echo sprintf("[NOTICE]: Class %s  was rewritten by the class %s \n",
                $class, $rewriteOptions['class']);
        }
        if (!empty($rewriteOptions['methods'])) {
            foreach ($rewriteOptions['methods'] as $method) {
                echo sprintf("[WARNING]: Method %s of class %s was rewritten by the class %s \n",
                    $method, $class, $rewriteOptions['class']);
            }
        }
    }
}

foreach ($codePoolClassRewrites as $codePoolClassRewrite) {
    echo sprintf("[NOTICE]: Class %s was rewritten in community or local pool \n",
         $codePoolClassRewrite);
}

if (!(count($xmlClassRewrites) > 0) || (count($codePoolClassRewrites) > 0)) {
    echo sprintf('No important classes and methods that affirm uses were overwritten.');
}
