<?php
/** @var Affirm_Affirm_Block_Adminhtml_Compatibility_Tool $this **/
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-compatibility"><?php echo $this->getHeader() ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getRunButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
<form name="compatibility_form" id="compatibility_form">
    <div id="error_validation_message"> </div>
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->helper('affirm')->__('Affirm Compatibility Tool'); ?></h4>
    </div>
    <fieldset>
        <table cellspacing="0" class="form-list" style="width:100%">
            <tr>
                <td class="label"><label ><?php echo $this->helper('affirm')->__('Direct Impacts'); ?></label></td>
                <td class="value">
                    <p>
                        <textarea id="validation_class" style="width:70%" readonly="readonly" cols="5" rows="3"> </textarea>
                    </p>
                </td>
            </tr>
            <tr>
                <td class="label"><label ><?php echo $this->helper('affirm')->__('Events'); ?></label></td>
                <td class="value">
                    <p>
                        <textarea id="validation_event" style="width:70%" readonly="readonly" cols="5" rows="3"> </textarea>
                    </p>
                </td>
            </tr>
            <tr>
                <td class="label"><label ><?php echo $this->helper('affirm')->__('Compiler'); ?></label></td>
                <td class="value">
                    <p>
                        <textarea id="validation_compiler"  style="width:70%" readonly="readonly" cols="5" rows="3"> </textarea>
                    </p>
                </td>
            </tr>
        </table>
    </fieldset>
</form>
</div>
