<?php
$mfpValue = $this->getMFPValue();
$learnMore = ($this->helper('affirm/promo_asLowas')->isVisibleLearnMore()) ? 'true' : 'false';
?>
<div>
    <?php echo '<div class="affirm-as-low-as" ' . (!empty($mfpValue) ? 'data-promo-id="' . $mfpValue . '"' : '') . ' data-amount="' . $this->getCheckoutGrandTotal() .'" data-learnmore-show="'.$learnMore.'"></div>'; ?>
</div>

<script type="text/javascript">
    if (!AFFIRM_AFFIRM.promos.getIsInitialized()) {
        AFFIRM_AFFIRM.promos.initialize("<?php echo $this->helper('affirm')->getApiKey(); ?>",
            "<?php echo $this->helper('affirm')->getAffirmJsUrl(); ?>");
    }
    <?php if ($this->helper('affirm')->isProductConfigurable()): ?>
    if (!AFFIRM_AFFIRM.promos.getIsConfigurableOptionsInitialized()) {
        AFFIRM_AFFIRM.promos.initConfigurableOptions(<?php echo $this->helper('affirm')->getConfigurableBackOrderedInfo(); ?>);
    }
    <?php endif; ?>
    AFFIRM_AFFIRM.promos.initLimitation("<?php echo $this->helper('affirm')->getMinOrderThreshold(); ?>", "<?php echo $this->helper('affirm')->getMaxOrderThreshold(); ?>");

    if (!AFFIRM_AFFIRM.promos.getIsScriptLoaded()) {
        AFFIRM_AFFIRM.promos.loadScript();
    }
</script>