<?php
    $mfpValue = $this->getMFPValue();
    $productId = $this->getProductId();
?>
<div>
    <?php echo '<div style="margin-bottom:5px;" class="affirm-as-low-as" id="as-low-as-refreshable" ' . (!empty($mfpValue) ? 'data-promo-id="' . $mfpValue . '"' : '') . ' data-amount="' . $this->getFinalPrice() .'"></div>'; ?>
</div>

<script type="text/javascript">
    if (!AFFIRM_AFFIRM.promos.getIsInitialized()) {
        AFFIRM_AFFIRM.promos.initialize("<?php echo $this->helper('affirm')->getApiKey(); ?>",
            "<?php echo $this->helper('affirm')->getAffirmJsUrl(); ?>");
    }
    <?php if ($this->helper('affirm')->isProductConfigurable()): ?>
    if (!AFFIRM_AFFIRM.promos.getIsConfigurableOptionsInitialized()) {
        AFFIRM_AFFIRM.promos.initConfigurableOptions(<?php echo $this->helper('affirm')->getConfigurableBackOrderedInfo(); ?>);
    }
    <?php endif; ?>
    AFFIRM_AFFIRM.promos.initLimitation("<?php echo $this->helper('affirm')->getMinOrderThreshold(); ?>", "<?php echo $this->helper('affirm')->getMaxOrderThreshold(); ?>");

    if (!AFFIRM_AFFIRM.promos.getIsScriptLoaded()) {
        AFFIRM_AFFIRM.promos.loadScript();
    }
</script>
<script type="text/javascript">
    jQuery(".bundle-option-select").on('change', function () {
        if(jQuery('#product-price-'+<?php echo $productId; ?>)) {
            var refreshable = document.getElementById('as-low-as-refreshable');
            var amount = jQuery('#product-price-' +<?php echo $productId; ?>).html();
            var finalAmount = Number(amount.replace(/[^0-9\.-]+/g,"")) * 100;
            refreshable.setAttribute('data-amount', finalAmount);
            console.log('refreshALA', refreshable);
            affirm.ui.refresh();
        }
    });
</script>